name: ci-cd

on:  
  push:
    branches: ["main"]
  workflow_dispatch: # Allows triggering the workflow manually

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve code
        uses: actions/checkout@v4.2.2

      - name: Authenticate in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Ensure this is set in repository secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Docker Hub PAT stored as a secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src          # Path to the directory containing the Dockerfile
          file: ./src/Dockerfile  # Explicitly specify the Dockerfile location
          push: true
          tags: torresj04/primeira-pipeline-cicd:latest, torresj04/primeira-pipeline-cicd:v1
      - name: Docker Image Builder
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
           torresj04/k8s-pipeline:v${{ github.run_number }}
           torresj04/k8s-pipeline:latest