name: ci-cd
on:  
  push:
    branches: ["main"]
  workflow_dispatch: ## allows to trigger the workflow manually
jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
      - name: Retrieve code
        uses: actions/checkout@v4.2.2
      - name: Authenticate in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

