name: ci-cd

on:  
  push:
    branches: ["main"]
  workflow_dispatch: # Allows triggering the workflow manually

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve code
        uses: actions/checkout@v4.2.2

      - name: Authenticate in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Ensure this is set in repository secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Docker Hub PAT stored as a secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src          # Path to the directory containing the Dockerfile
          file: ./src/Dockerfile  # Explicitly specify the Dockerfile location
          push: true
          tags: torresj04/primeira-pipeline-cicd:latest, torresj04/primeira-pipeline-cicd:v1

      - name: Docker Image Builder
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            torresj04/k8s-pipeline:v${{ github.run_number }}
            torresj04/k8s-pipeline:latest

  CD: 
    # 1- Setup kubeconfig
    # 2- Execute kubectl apply
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Retrieve code
        uses: actions/checkout@v4.2.2

      - name: Configuring kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: <your kubeconfig>
          context: ${{ secrets.K8S_CONFIG }}  # current-context from kubeconfig is used as default

      - name: Manifest run
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: torresj04/k8s-pipeline:v${{ github.run_number }}